import { defineLocalBusiness } from '@unhead/schema-org';

/**
 * Demonstrates the LAB title helper.
 *
 * @since August 13, 2026
 */
export default class Lab {

	/**
	 * Provides LAB demonstration page data.
	 *
	 * @since August 13, 2026
	 *
	 * @return {object} LAB page data.
	 */
	data() {
		return {
			layout: 'layouts/Page.11ty.js',
			permalink: '/lab/',
			title: 'Lab',
			description: 'A demonstration of the LAB-style title helper.',
			eleventyComputed: {

				/**
				 * Builds the LAB title for this page.
				 *
				 * @since August 13, 2026
				 *
				 * @param {object} data Eleventy data cascade.
				 * @return {string} LAB-style page title.
				 */
				title ( data ) {
					return data.fn.labTitle( data, 'Lab' );
				},

				/**
				 * Defines the LocalBusiness schema for this page.
				 *
				 * @since August 13, 2026
				 *
				 * @param {object} data Eleventy data cascade.
				 * @return {object} LocalBusiness schema data.
				 */
				pageSchema ( data ) {
					return {
						LocalBusiness: defineLocalBusiness( {
							...data.schema.localBusiness,
							url: data.metadata.url,
						} ),
					};
				},
			},
			eleventyNavigation: {
				key: 'Lab',
				title: 'Lab',
				order: 5,
			},
		};
	}

	/**
	 * Renders the LAB title demonstration.
	 *
	 * @since August 13, 2026
	 *
	 * @param {object} data Eleventy data cascade.
	 * @return {string} LAB page HTML.
	 */
	render( data ) {
		return /* html */ `
			<h1>LAB title helper</h1>
			<p>This page demonstrates the title format generated by <code>data.fn.labTitle( data, title )</code>.</p>
			<p><strong>Generated title:</strong> ${ data.fn.escHtml( data.fn.labTitle( data, data.title ) ) }</p>
		`;
	}
}
